#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Team:
#   J Phani Mahesh <phanimahesh@gmail.com>
#   Barneedhar (jokerdino) <barneedhar@ubuntu.com>
#   Amith KK <amithkumaran@gmail.com>
#   Georgi Karavasilev <motorslav@gmail.com>
#   Sam Tran <samvtran@gmail.com>
#   Sam Hewitt <hewittsamuel@gmail.com>
#
# Description:
#   A One-stop configuration tool for Unity.
#
# Legal Stuff:
#
# This file is a part of Unity Tweak Tool
#
# Unity Tweak Tool is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; version 3.
#
# Unity Tweak Tool is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, see <https://www.gnu.org/licenses/gpl-3.0.txt>

import os, os.path, argparse, sys, dbus, dbus.service
from dbus.mainloop.glib import DBusGMainLoop
from gi.repository import Gtk, Gio, Unity, Dbusmenu, Dee

from unitytweak.ui import ui
from unitytweak.start import Startpage
from unitytweak.unity import Unitysettings
from unitytweak.compiz import Compizsettings
from unitytweak.theme import Themesettings
from unitytweak.desktop import Desktopsettings
from unitytweak.about import About
from unitytweak import unitytweakconfig

DBusGMainLoop(set_as_default=True)

class UnityTweak (dbus.service.Object):
    def __init__(self):
        '''Handler Initialisations.
        Obtain all references here.'''
        self.builder = Gtk.Builder()
        self.glade = (os.path.join(unitytweakconfig.get_data_path(),
                                    'unitytweak.ui'))
        self.builder.add_from_file(self.glade)
        self.ui = ui(self.builder)

        self.builder.connect_signals(self)
        self.ui['unitytweak_main'].set_resizable(False)

        self.launcher = Unity.LauncherEntry.get_for_desktop_id("unity-tweak-tool.desktop")

        # Symbolic icons
        self.icons = Gtk.IconTheme.get_default()
        self.style_context = self.ui['toolbar_main'].get_style_context()
        self.style_context.add_class(Gtk.STYLE_CLASS_PRIMARY_TOOLBAR)
        self.style_context.connect('changed', self.on_style_context_change)

        self.notebook = self.ui['nb_unitytweak']

        self.startpage = Startpage(self.ui, self.notebook)
        self.unitysettings = Unitysettings(self.ui)
        self.compizsettings = Compizsettings(self.ui)
        self.themesettings = Themesettings(self.ui)
        self.desktopsettings = Desktopsettings(self.ui)

        self.notebook.append_page(self.startpage.page, None)
        self.notebook.append_page(self.unitysettings.page, None)
        self.notebook.append_page(self.compizsettings.page, None)
        self.notebook.append_page(self.themesettings.page, None)
        self.notebook.append_page(self.desktopsettings.page, None)

        self.ui['unitytweak_main'].show_all()
        self.ui['unitytweak_main'].connect("delete-event", Gtk.main_quit)


        # ===== Command line options: Start ===== #

        parser = argparse.ArgumentParser()

        parser.add_argument('-u', '--unity', help='Start in the Unity tab', action='store_true')
        parser.add_argument('-w', '--winmng', help='Start in the WindowManager tab', action='store_true')
        parser.add_argument('-a', '--appearance', help='Start in the appearance tab', action='store_true')
        parser.add_argument('-s', '--system', help='Start in the system tab', action='store_true')

        args = parser.parse_args()

        if args.unity:
            self.check_running_instance('unity')
        elif args.winmng:
            self.check_running_instance('winmng')
        elif args.appearance:
            self.check_running_instance('appearance')
        elif args.system:
            self.check_running_instance('system')
        else: # No/wrong cmd args
            # FIXME: Will probably cause future problems?
            self.check_running_instance('overview')

        # ===== Command line options: End ===== #

        Gtk.main()

    def check_running_instance(self, cmd_arg):

        if not os.path.exists(os.path.expanduser('~/.config/unity-tweak-tool/')):
            os.makedirs(os.path.expanduser('~/.config/unity-tweak-tool/'))

        if os.access(os.path.expanduser("~/.config/unity-tweak-tool/pid.lockfile"), os.F_OK):
            pidfile = open(os.path.expanduser("~/.config/unity-tweak-tool/pid.lockfile"), "r")
            pidfile.seek(0)
            old_pd = pidfile.readline()
            if os.path.exists("/proc/%s" % old_pd):

                self.call_running_instance(cmd_arg)
                sys.exit(1)
            else:
                os.remove(os.path.expanduser("~/.config/unity-tweak-tool/pid.lockfile"))

        pidfile = open(os.path.expanduser("~/.config/unity-tweak-tool/pid.lockfile"), "w")
        pidfile.write("%s" % os.getpid())
        pidfile.close()
        self.register_dbus_session()
        self.dbus_callback(cmd_arg)

    def call_running_instance(self, cmd_arg):

        bus = dbus.SessionBus()
        service = bus.get_object('org.freyja.utt', '/org/freyja/utt')
        callback_method = service.get_dbus_method('dbus_callback', 'org.freyja.utt')
        callback_method(cmd_arg)

    @dbus.service.method('org.freyja.utt', in_signature='s')

    def dbus_callback(self, cmd_arg):

        if(cmd_arg == 'overview'):
            self.notebook.set_current_page(0)

        elif(cmd_arg == 'unity'):
            self.notebook.set_current_page(1)

        elif (cmd_arg == 'winmng'):
            self.notebook.set_current_page(2)

        elif (cmd_arg == 'appearance')    :
            self.notebook.set_current_page(3)

        elif (cmd_arg == 'system'):
            self.notebook.set_current_page(4)

    def register_dbus_session(self):
        bus_name = dbus.service.BusName('org.freyja.utt', bus=dbus.SessionBus())
        dbus.service.Object.__init__(self, bus_name, '/org/freyja/utt')

    def page_changed(self, controls, page, page_id):
        ''' Called when the current visible section changes '''
        for item_id, item in enumerate(self.section_menu):
            # Check the current section's menu item, unchecking all others
            if item_id == page_id:
                item.property_set_int(Dbusmenu.MENUITEM_PROP_TOGGLE_STATE, Dbusmenu.MENUITEM_TOGGLE_STATE_CHECKED)
            else:
                item.property_set_int(Dbusmenu.MENUITEM_PROP_TOGGLE_STATE, Dbusmenu.MENUITEM_TOGGLE_STATE_UNCHECKED)

    def section_menu_item_activated(self, menu_item, obj, page_id):
        ''' Called when a Quicklist menu item is selected '''
        self.notebook.set_current_page(page_id)
        if page_id == 0:
            self.notebook.set_current_page(page_id)
        elif page_id == 1:
            self.notebook.set_current_page(page_id)
        elif page_id == 2:
            self.notebook.set_current_page(page_id)
        elif page_id == 3:
            self.notebook.set_current_page(page_id)
        elif page_id == 4:
            self.notebook.set_current_page(page_id)
        else:
            self.notebook.set_current_page(page_id)

    # ===== Menu Bar ===== #

    # ----- Unity Menu ----- #
    def on_menuitem_unity_launcher_activate(self,udata):
        self.notebook.set_current_page(1)
        self.unitysettings.page.set_current_page(0)

    def on_menuitem_unity_dash_activate(self,udata):
        self.notebook.set_current_page(1)
        self.unitysettings.page.set_current_page(1)

    def on_menuitem_unity_panel_activate(self,udata):
        self.notebook.set_current_page(1)
        self.unitysettings.page.set_current_page(2)

    def on_menuitem_unity_switcher_activate(self,udata):
        self.notebook.set_current_page(1)
        self.unitysettings.page.set_current_page(3)

    def on_menuitem_unity_additional_activate(self,udata):
        self.notebook.set_current_page(1)
        self.unitysettings.page.set_current_page(4)

    # ----- Compiz Settings Menu ----- #
    def on_menuitem_compiz_general_activate(self,udata):
        self.notebook.set_current_page(2)
        self.compizsettings.page.set_current_page(0)

    def on_menuitem_compiz_workspace_activate(self,udata):
        self.notebook.set_current_page(2)
        self.compizsettings.page.set_current_page(1)

    def on_menuitem_compiz_windows_spread_activate(self,udata):
        self.notebook.set_current_page(2)
        self.compizsettings.page.set_current_page(2)

    def on_menuitem_compiz_windows_snapping_activate(self,udata):
        self.notebook.set_current_page(2)
        self.compizsettings.page.set_current_page(3)

    def on_menuitem_compiz_hotcorners_activate(self,udata):
        self.notebook.set_current_page(2)
        self.compizsettings.page.set_current_page(4)

    # ----- Appearance Settings Menu ----- #
    def on_menuitem_theme_system_activate(self,udata):
        self.notebook.set_current_page(3)
        self.themesettings.page.set_current_page(0)

    def on_menuitem_theme_icon_activate(self,udata):
        self.notebook.set_current_page(3)
        self.themesettings.page.set_current_page(1)

    def on_menuitem_theme_cursor_activate(self,udata):
        self.notebook.set_current_page(3)
        self.themesettings.page.set_current_page(2)

    def on_menuitem_theme_fonts_activate(self,udata):
        self.notebook.set_current_page(3)
        self.themesettings.page.set_current_page(3)

    # ----- System Settings Menu ----- #
    def on_menuitem_desktop_icons_activate(self,udata):
        self.notebook.set_current_page(4)
        self.desktopsettings.page.set_current_page(0)

    def on_menuitem_system_security_activate(self,udata):
        self.notebook.set_current_page(4)
        self.desktopsettings.page.set_current_page(1)

    def on_menuitem_scrolling_activate(self,udata):
        self.notebook.set_current_page(4)
        self.desktopsettings.page.set_current_page(2)

    # ----- Top Navigation bar ----- #
    def on_b_overview_clicked(self,udata):
        self.notebook.set_current_page(0)

    # Symbolic icon
    def on_style_context_change(self, widget):
        self.main_fg_color = self.style_context.get_color(Gtk.StateFlags.ACTIVE)
        symbolic_icon = self.icons.lookup_icon('unity-tweak-tool-overview-symbolic', 24, Gtk.IconLookupFlags.FORCE_SIZE)
        if symbolic_icon:
            symbolic_icon_pixbuf, was_sym = symbolic_icon.load_symbolic(self.main_fg_color, None, None, None)
            self.ui['image_overview'].set_from_pixbuf(symbolic_icon_pixbuf)

    # ===== GTK Search Box =====

    # inserting text shows the secondary icon (stock-clear)

    def on_tool_entry_search_insert_text(self,text,length,position,udata):

        # getting the text length to workaround some Gtk bug
        if self.ui['tool_entry_search'].get_text_length()+1:
            self.ui['tool_entry_search'].set_icon_from_stock(Gtk.EntryIconPosition.SECONDARY,
                Gtk.STOCK_CLEAR)

        else:
            self.ui['tool_entry_search'].set_icon_from_stock(Gtk.EntryIconPosition.SECONDARY, None)

    def on_tool_entry_search_delete_text(self,start_pos,end_pos,udata):

        # getting the text length to workaround some Gtk bug

        if (self.ui['tool_entry_search'].get_text_length()-1) == 0:
            self.ui['tool_entry_search'].set_icon_from_stock(Gtk.EntryIconPosition.SECONDARY, None)

    # clicking on secondary icon clearing text

    def on_tool_entry_search_icon_press(self, widget, icon, mouse_button):

        if icon == Gtk.EntryIconPosition.SECONDARY:
            widget.set_text("")
            widget.set_icon_from_stock(Gtk.EntryIconPosition.SECONDARY, None)

        if icon == Gtk.EntryIconPosition.PRIMARY:
            print("Searching")

    # setting up menus

    def on_menuimage_about_activate(self, widget):
        self.about = About(self.ui)

    def on_menuimage_quit_activate(self, widget):
        Gtk.main_quit()

if __name__=='__main__':
# Fire up the Engines
    UnityTweak()
else:
    print("WARNING: This module is not tailored to be imported. Proceed at your own risk.")
