#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Team:
#   J Phani Mahesh <phanimahesh@gmail.com> 
#   Barneedhar (jokerdino) <barneedhar@ubuntu.com> 
#   Amith KK <amithkumaran@gmail.com>
#   Georgi Karavasilev <motorslav@gmail.com>
#   Sam Tran <samvtran@gmail.com>
#   Sam Hewitt <hewittsamuel@gmail.com>
#
# Description:
#   A One-stop configuration tool for Unity.
#
# Legal Stuff:
#
# This file is a part of Unity Tweak Tool
#
# Unity Tweak Tool is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; version 3.
#
# Unity Tweak Tool is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, see <https://www.gnu.org/licenses/gpl-3.0.txt>

import os, os.path, argparse

from gi.repository import Gtk, Gio, Unity, Dbusmenu, Dee

from unitytweak.ui import ui
from unitytweak.start import Startpage
from unitytweak.unity import Unitysettings
from unitytweak.compiz import Compizsettings
from unitytweak.theme import Themesettings
from unitytweak.desktop import Desktopsettings
from unitytweak.about import About
from unitytweak import settings

class UnityTweak ():
    def __init__(self):
        '''Handler Initialisations.
        Obtain all references here.'''
        self.builder = Gtk.Builder()
        self.glade = (os.path.join(settings.UI_DIR,
                                    'unitytweak.ui'))
        self.builder.add_from_file(self.glade)
        self.ui = ui(self.builder)

        self.builder.connect_signals(self)
        self.ui['unitytweak_main'].set_resizable(False)

        self.launcher = Unity.LauncherEntry.get_for_desktop_id("unity-tweak-tool.desktop")

        self.notebook = self.ui['nb_unitytweak']

        self.startpage = Startpage(self.ui, self.notebook)
        self.unitysettings = Unitysettings(self.ui)
        self.compizsettings = Compizsettings(self.ui)
        self.themesettings = Themesettings(self.ui)
        self.desktopsettings = Desktopsettings(self.ui)

        self.notebook.append_page(self.startpage.page, None)
        self.notebook.append_page(self.unitysettings.page, None)
        self.notebook.append_page(self.compizsettings.page, None)
        self.notebook.append_page(self.themesettings.page, None)
        self.notebook.append_page(self.desktopsettings.page, None)

        self.ui['unitytweak_main'].show_all()
        self.ui['unitytweak_main'].connect("delete-event", Gtk.main_quit)


        #---------- Command line options: Start ----------------------

        parser = argparse.ArgumentParser()

        parser.add_argument('-u', '--unity', help='Start in the Unity tab', action='store_true')
        parser.add_argument('-w', '--winmng', help='Start in the WindowManager tab', action='store_true')
        parser.add_argument('-a', '--appearance', help='Start in the appearance tab', action='store_true')
        parser.add_argument('-s', '--system', help='Start in the system tab', action='store_true')
        parser.add_argument('-r', '--restore', help='Restore settings to its default values', action='store_true')

        args = parser.parse_args()

        if args.unity:
            self.ui['tool_unitysettings'].set_active(True)            
        elif args.winmng:
            self.ui['tool_compizsettings'].set_active(True)            
        elif args.appearance:
            self.ui['tool_themesettings'].set_active(True)        
        elif args.system:
            self.ui['tool_desktopsettings'].set_active(True)            
        elif args.restore:
            #TODO : Restore everything in one call
            print()

        #----------- Command line options: End -----------------------



        # ===== Quicklist =====
        quicklist = Dbusmenu.Menuitem.new()
        sections = ['Overview', 'Unity', 'Window Manager', 'Appearance', 'System']
        self.section_menu = [None, None, None, None, None, None]
        for page_id, page_name in enumerate(sections):

            # Create a new item for this section
            section_menu_item = Dbusmenu.Menuitem.new ()

            # Set the page's name as the menu item's name
            section_menu_item.property_set (Dbusmenu.MENUITEM_PROP_LABEL, page_name)

            # Make the menu item toggle-able
            section_menu_item.property_set(Dbusmenu.MENUITEM_PROP_TOGGLE_TYPE, Dbusmenu.MENUITEM_TOGGLE_RADIO)

            # Make the menu item visible
            section_menu_item.property_set_bool (Dbusmenu.MENUITEM_PROP_VISIBLE, True)

            # When the menu item is clicked, make it call menu_item_activated
            # with the page id, which is used to make that the active page
            section_menu_item.connect('item_activated', self.section_menu_item_activated, page_id)

            # Add the section's menu item to the Quicklist menu
            quicklist.child_append(section_menu_item)
            self.section_menu[page_id] = section_menu_item

        # Listen for the user changing pages
        self.ui['nb_unitytweak'].connect('change-current-page', self.page_changed)
        
        # Apply the quickist to the Launcher icon
        self.launcher.set_property('quicklist', quicklist)

        Gtk.main()
    

    def page_changed(self, controls, page, page_id):
        ''' Called when the current visible section changes '''
        for item_id, item in enumerate(self.section_menu):
            # Check the current section's menu item, unchecking all others
            if item_id == page_id:
                item.property_set_int(Dbusmenu.MENUITEM_PROP_TOGGLE_STATE, Dbusmenu.MENUITEM_TOGGLE_STATE_CHECKED)
            else:
                item.property_set_int(Dbusmenu.MENUITEM_PROP_TOGGLE_STATE, Dbusmenu.MENUITEM_TOGGLE_STATE_UNCHECKED)
        
    def section_menu_item_activated(self, menu_item, obj, page_id):
        ''' Called when a Quicklist menu item is selected '''
        self.notebook.set_current_page(page_id)
        if page_id == 0:
            self.ui['tool_startpage'].set_active(True)            
        elif page_id == 1:
            self.ui['tool_unitysettings'].set_active(True)            
        elif page_id == 2:
            self.ui['tool_compizsettings'].set_active(True)            
        elif page_id == 3:
            self.ui['tool_themesettings'].set_active(True)        
        elif page_id == 4:
            self.ui['tool_desktopsettings'].set_active(True)            
        else:
            self.ui['tool_startpage'].set_active(True) 
        
    # ===== Menu Bar ==== #
    
    # ===== Unity Menu ==== #
    def on_menuitem_unity_launcher_activate(self,udata):
        self.notebook.set_current_page(1)
        self.unitysettings.page.set_current_page(0)

    def on_menuitem_unity_dash_activate(self,udata):
        self.notebook.set_current_page(1)
        self.unitysettings.page.set_current_page(1)
 
    def on_menuitem_unity_panel_activate(self,udata):
        self.notebook.set_current_page(1)
        self.unitysettings.page.set_current_page(2)
		
    def on_menuitem_unity_switcher_activate(self,udata):
        self.notebook.set_current_page(1)
        self.unitysettings.page.set_current_page(3)
		
    def on_menuitem_unity_additional_activate(self,udata):
        self.notebook.set_current_page(1)
        self.unitysettings.page.set_current_page(4)
        
    # ===== Compiz Settings Menu ==== #
    def on_menuitem_compiz_general_activate(self,udata):
        self.notebook.set_current_page(2)
        self.compizsettings.page.set_current_page(0)
        
    def on_menuitem_compiz_workspace_activate(self,udata):
        self.notebook.set_current_page(2)
        self.compizsettings.page.set_current_page(1)
        
    def on_menuitem_compiz_windows_spread_activate(self,udata):
        self.notebook.set_current_page(2)
        self.compizsettings.page.set_current_page(2)
        
    def on_menuitem_compiz_windows_snapping_activate(self,udata):
        self.notebook.set_current_page(2)
        self.compizsettings.page.set_current_page(3)
        
    def on_menuitem_compiz_hotcorners_activate(self,udata):
        self.notebook.set_current_page(2)
        self.compizsettings.page.set_current_page(4)

    # ===== Appearance Settings Menu ==== #
    def on_menuitem_theme_system_activate(self,udata):
        self.notebook.set_current_page(3)
        self.themesettings.page.set_current_page(0)

    def on_menuitem_theme_icon_activate(self,udata):
        self.notebook.set_current_page(3)
        self.themesettings.page.set_current_page(1)

    def on_menuitem_theme_cursor_activate(self,udata):
        self.notebook.set_current_page(3)
        self.themesettings.page.set_current_page(2)

    def on_menuitem_theme_fonts_activate(self,udata):
        self.notebook.set_current_page(3)
        self.themesettings.page.set_current_page(3)

    # ===== System Settings Menu ==== #
    def on_menuitem_desktop_icons_activate(self,udata):
        self.notebook.set_current_page(4)
        self.desktopsettings.page.set_current_page(0)

    def on_menuitem_system_security_activate(self,udata):
        self.notebook.set_current_page(4)
        self.desktopsettings.page.set_current_page(1)

    def on_menuitem_scrolling_activate(self,udata):
        self.notebook.set_current_page(4)
        self.desktopsettings.page.set_current_page(2)

    # ===== Top Navigation bar =====
    def on_tool_startpage_toggled(self,udata):
        self.notebook.set_current_page(0)
    def on_tool_unitysettings_toggled(self,udata):
        self.notebook.set_current_page(1)
        self.unitysettings.page.set_current_page(0)
    def on_tool_compizsettings_toggled(self,udata):
        self.notebook.set_current_page(2)
        self.compizsettings.page.set_current_page(0)
    def on_tool_themesettings_toggled(self,udata):
        self.notebook.set_current_page(3)
        self.themesettings.page.set_current_page(0)
    def on_tool_desktopsettings_toggled(self,udata):
        self.notebook.set_current_page(4)

    # ===== GTK Search Box =====

    # inserting text shows the secondary icon (stock-clear)

    def on_tool_entry_search_insert_text(self,text,length,position,udata):

        # getting the text length to workaround some Gtk bug
        if self.ui['tool_entry_search'].get_text_length()+1:
            self.ui['tool_entry_search'].set_icon_from_stock(Gtk.EntryIconPosition.SECONDARY,
                Gtk.STOCK_CLEAR)

        else:
            self.ui['tool_entry_search'].set_icon_from_stock(Gtk.EntryIconPosition.SECONDARY, None)

    def on_tool_entry_search_delete_text(self,start_pos,end_pos,udata):

        # getting the text length to workaround some Gtk bug

        if (self.ui['tool_entry_search'].get_text_length()-1) == 0:
            self.ui['tool_entry_search'].set_icon_from_stock(Gtk.EntryIconPosition.SECONDARY, None)

    # clicking on secondary icon clearing text

    def on_tool_entry_search_icon_press(self, widget, icon, mouse_button):

        if icon == Gtk.EntryIconPosition.SECONDARY:
            widget.set_text("")
            widget.set_icon_from_stock(Gtk.EntryIconPosition.SECONDARY, None)

        if icon == Gtk.EntryIconPosition.PRIMARY:
            print("Searching")

    # setting up menus

    def on_menuimage_about_activate(self, widget):
        self.about = About(self.ui)

    def on_menuimage_quit_activate(self, widget):
        Gtk.main_quit()

if __name__=='__main__':
# Fire up the Engines
    UnityTweak()
else:
    print("WARNING: This module is not tailored to be imported. Proceed at your own risk.")
